# Generated by Django 4.1 on 2022-09-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name_plural': 'Food Categories'},
        ),
        migrations.AlterModelOptions(
            name='fooditems',
            options={'verbose_name_plural': 'Food Items'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='homepage.foodcategory'),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
