# Generated by Django 4.1 on 2022-09-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_cartitems_options_alter_foodcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
