# Generated by Django 4.1 on 2022-09-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_fooditems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='stock',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
